espacofacil_api/espacofacil_api/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views import occupancy_create,occupancy_create_multiple, occupancy_delete, occupancy_update, occupancy_view, login_view
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView



from app.views import (
    RoomListView, room_create, room_update,RoomDeleteView,RoomDetailView,
    UserListView, UserCreateView, UserUpdateView, UserDeleteView, UserPasswordResetView,
    EquipmentListView,EquipmentCreateView,EquipmentUpdateView,EquipmentDeleteView,
    RoomSearchView,get_scheduled_dates)      

urlpatterns = [
    path('', RedirectView.as_view(url='/accounts/login/', permanent=False)),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),  # <--- Aqui
    # path('login/', login_view, name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('home/', RoomSearchView.as_view(), name="home"),
    path('roomList/', RoomListView.as_view(),name="room_list"),
    path('roomCreate/', room_create,name="room_create"),
    path('updateRoom/<int:pk>/', room_update, name="room_update"),
    path('deleteRoom/<int:pk>/', RoomDeleteView.as_view(), name="room_delete"),
    path('userList/', UserListView.as_view(), name="user_list"),
    path('userCreate/', UserCreateView.as_view(), name="user_create"),
    path('updateUser/<int:pk>/', UserUpdateView.as_view(), name="user_update"),
    path('deleteUser/<int:pk>/', UserDeleteView.as_view(), name="user_delete"),
    path('userPasswordReset/<int:pk>/', UserPasswordResetView.as_view(), name="user_password_reset"),
    path('equipmentList/', EquipmentListView.as_view(), name="equipment_list"),
    path('equipmentCreate/', EquipmentCreateView.as_view(),name="equipment_create"),
    path('updateEquipmnet/<int:pk>/',EquipmentUpdateView.as_view(),name="equipment_update"),
    path('deleteEquipmnet/<int:pk>/',EquipmentDeleteView.as_view(),name="equipment_delete"),
    path('room/<int:pk>/', RoomDetailView.as_view(), name="room_detail"),
    path('OccupancyCreate/<int:idRoom>/',occupancy_create,name="occupancy_create"),
    path('OccupancyCreateMultiple/<int:idRoom>/', occupancy_create_multiple, name='occupancy_create_multiple'),
    path("OccupancyDelete/<int:idOccupancy>/",occupancy_delete,name="occupancy_delete"),
    path("OccupancyUpdate/<int:idOccupancy>/",occupancy_update,name='occupancy_update'),
    path('occupancys_list/<int:idRoom>',occupancy_view,name="occupancy_list"),
    path('api/scheduled-dates/<int:idRoom>/<int:year>/<int:month>/', get_scheduled_dates, name='get_scheduled_dates'),
] 

espacofacil_api/app/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.core.validators import MinLengthValidator
from django.db import models
from datetime import timedelta, datetime, time

# Create your models here.
class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('Email é obrigatório')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)  # 🔒 Usa hash seguro
        user.save(using=self._db)
        return user
    
    # user_type = models.ForeignKey('UserType', on_delete=models.CASCADE, null=True, blank=True)


    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=15)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    def __str__(self):
        return self.email

class Equipment(models.Model):
    nameEquipment = models.CharField(max_length=200)
    
    def __str__(self):
        return {self.nameEquipment}


class Room(models.Model):
    roomManager = models.ForeignKey(User,on_delete=models.CASCADE)
    nameRoom = models.CharField(max_length=100, null=False, blank=False)
    headCount = models.IntegerField(null=False, blank=False)
    def __str__(self):
        return f'{self.nameRoom} pode conter {self.headCount} indivíduos'
    

class RoomTimeSlot(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, null=True)
    time_start = models.TimeField(null=False, blank=False)
    time_end = models.TimeField(null=False, blank=False)
    interval = models.PositiveIntegerField(default=60)  # assume minutos

    def save(self, *args, **kwargs):
        # Converte time_start e time_end em minutos desde 00:00
        start_minutes = self.time_start.hour * 60 + self.time_start.minute
        end_minutes = self.time_end.hour * 60 + self.time_end.minute
        total_duration_minutes = end_minutes - start_minutes

        if self.interval <= total_duration_minutes:
            super().save(*args, **kwargs)
        else:
            raise ValueError("Intervalo não pode ser maior que a duração total!")




    

class RoomEquipment(models.Model):
    room = models.ForeignKey(Room,on_delete=models.CASCADE)
    equipment = models.ForeignKey(Equipment,on_delete=models.CASCADE)
    amount = models.IntegerField()

    def __str__(self):
        return self.equipment.nameEquipment

    

class Occupancy(models.Model):
    room = models.ForeignKey(Room,on_delete=models.CASCADE)
    occupant = models.CharField(max_length=100, verbose_name='Detalhes do Ocupante', null=True, blank=True)
    day = models.DateField(null=False,blank=True)
    time_start = models.TimeField(null=False, blank=False)
    time_end = models.TimeField(null=False, blank=False)
    status = models.BooleanField()

    def __str__(self):
        return f'Espaco reservado na data: {self.day}'

espacofacil_api/templates/app/calendar_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container-datetime">
    <div class="calendar-container">
        <div id="calendar" class="calendar"></div>
    </div>
    <div class="time-container">
        <div class="horario">
            <label for="hora">Hora:</label>
            <input type="number" id="hora" name="hora" min="0" max="23" placeholder="00">
    
            <label for="minuto">Minuto:</label>
            <input type="number" id="minuto" name="minuto" min="0" max="59" placeholder="00">

            <!-- <button id="edit-time">Editar Horário</button>
            <button id="delete-time">Cancelar Horário</button> -->
        </div>
        
    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/pt.js"></script>
<script src="{% static 'js/calendar.js' %}"></script>
<script>
  

</script>
{% endblock %}

espacofacil_api/templates/app/equipment_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<h1>Excluindo Equipamento</h1>

    <h3 class="h3">Excluir Equipamento?</h3>
    <hr>
    <p class="lead">Tem certeza que deseja excluir esse equipamento:  <strong> {{equipment.nameEquipment}} </strong> ?</p>
    <form method="POST">
        {% csrf_token %}
        <div class="row g-3">
            <div class="offset-8 col-2">
                <a href="javascript:history.back()" class="btn btn-primary btn-lg">Cancelar</a>
            </div>
            <div class="col-2">
                <button type="submit" class="btn btn-danger btn-lg" style="width: 100%;">Excluir Espaço</button>
            </div>
        </div>
    </form>
{% endblock content %}


    

espacofacil_api/templates/app/equipment_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div>
    {% if equipment.pk %}
        <h1>Editando Equipamento</h1>
    {% else %}
        <h1>Adicionando Equipamento</h1>
    {% endif %}

<form method="post">
    {% csrf_token %}
    <legend class="h4">Detalhes do Equipamento</legend>
    <hr>
    {{ form|crispy }}
    <div class="row g-3">
        <div class="offset-8 col-2">
            <a href="javascript:history.back()" class="btn btn-danger btn-lg">Cancelar</a>
        </div>
        <div class="col-2">
            <button type="submit" class="btn btn-success btn-lg" style="width: 100%;">Salvar</button>
        </div>
    </div>
</form>
{% endblock content %}
</div>  

espacofacil_api/templates/app/equipment_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="table-container">
  <h1>Equipamentos</h1>
  <button class="button-registry">
    <a href={% url "equipment_create" %}>+ Adicionar Equipamento</a>
  </button>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nome do equipamento</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody>
        {% for equipment in equipment_list %}
        <tr>
            <th scope="row">{{equipment.pk}}</th>
            <td>{{equipment.nameEquipment}}</td>
            <td class="actions">
                <button class="btn btn-outline-primary" onclick="window.location.href='{% url 'equipment_update' pk=equipment.pk %}'">
                  Editar
                </button>
                
                <button class="btn btn-outline-danger" onclick="window.location.href='{% url 'equipment_delete' pk=equipment.pk %}'">
                  Excluir
                
                </button>
      
            </td>
          </tr>
        {% endfor %}
    </tbody>
  </table>
</div>

  
{% endblock content %}

espacofacil_api/templates/app/home.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-5">
    <h1>Buscando Espaços para Agendar</h1>
    <form method="get" class="row g-3">
      <div class="col-md-6">
        <label for="name" class="form-label">Nome do Espaço (separe por vírgulas):</label>
        <input type="text" class="form-control" id="name" name="name" placeholder="Ex: Espaço 101, Auditório" value="{{ request.GET.name}}">
      </div>
      <div class="col-md-6">
        <label for="equipments" class="form-label">Equipamentos (separe por vírgulas):</label>
        <input type="text" class="form-control" id="equipments" name="equipments" placeholder="Ex: Computador, Projetor" value="{{ request.GET.equipments}}">
      </div>
      <div class="col-md-3">
        <label for="headCount" class="form-label">Capacidade mínima:</label>
        <input type="number" class="form-control" id="headCount" name="headCount" min="1" value="{{request.GET.headCount}}">
      </div>
      <div class="col-md-3">
        <label for="date" class="form-label">Data:</label>
        <input type="date" class="form-control" id="date" name="date" value="{{ request.GET.date}}">
      </div>
      <div class="col-md-3">
        <label for="time_start" class="form-label">Hora início:</label>
        <input type="time" class="form-control" id="time_start" name="time_start" value="{{ request.GET.time_start}}">
      </div>
      <div class="col-md-3">
        <label for="time_end" class="form-label">Hora fim:</label>
        <input type="time" class="form-control" id="time_end" name="time_end" value="{{ request.GET.time_end}}">
      </div>
      <div class="col-12">
        <p style="color: gray;">Para pesquisar todos, clique em Pesquisar com todos os campos vazios.</p>
        <br>
        <div class="d-flex justify-content-between">
          <button type="submit" class="btn btn-primary">Pesquisar <i class="fa-solid fa-magnifying-glass"></i></button>
          <button type="button" class="btn btn-secondary" onclick="limparCampos()">Limpar campos de busca</button>
        </div>
      </div>

    </form>
</div>
<div>
    {% if request.GET %}
    <hr>
    <h3>Espaços Encontrados:</h3>
    <ul class="list-group">
      {% for room in rooms %}
        <li class="list-group-item">
          <strong>{{ room.nameRoom }}</strong> — Capacidade: {{ room.headCount }}<br>
          Gerente: {{ room.roomManager.name }}<br>
          Equipamentos:
          {% with room.roomequipment_set.all as equipment_list %}
            {% if equipment_list %}
              {{ equipment_list|join:", " }}
            {% else %}
              Nenhum equipamento
            {% endif %}
          {% endwith %}
          <button class="btn btn-success btn-sm">
            <a href={% url "occupancy_list" idRoom=room.pk %}>Agendar  <i class="fa-regular fa-calendar-plus"></i></a>
          </button>
        </li>
      {% empty %}
        <li class="list-group-item">Nenhum espaço encontrado com esses critérios.</li>
      {% endfor %}
    </ul>
  {% endif %}
</div>

<script>
function limparCampos() {
  document.querySelector('form').reset();
}
</script>
{% endblock content %}

espacofacil_api/templates/app/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <title>Login - Espaço Fácil</title>
  <link rel="stylesheet" href="{% static 'css/login.css' %}">
  <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
</head>

<body>
  <div class="container">
    <div class="logo-area">
        <img src="{% static 'images/LOGOLOGIN.png' %}" alt="Espaço Facil">
    </div>

    <div class="login-area">
      <form method="post" class="login-box">
        {% csrf_token %}
        <h2>Login</h2>

        <div class="form-group">
          {{ form.email.label_tag }}
          {{ form.email }}
          {{ form.email.errors }}
        </div>

        <div class="form-group">
          {{ form.password.label_tag }}
          {{ form.password }}
          {{ form.password.errors }}
        </div>

        <button type="submit" class="btn">Entrar</button>

        {% if form.non_field_errors %}
          <p style="color:red;">{{ form.non_field_errors }}</p>
        {% endif %}
      </form>
    </div>
  </div>
</body>
</html>

espacofacil_api/templates/app/occupancy_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
</head>
<form method="post">
    {% csrf_token %}
    <div></div>
    <fieldset>
        <h3 class="h3">Editando Agendamento</h3>
        {{ occupancyForm|crispy }}
    </fieldset>
    <div class="row g-3">
        <div class="offset-8 col-2">
            <a href="javascript:history.back()" class="btn btn-danger btn-lg">Cancelar</a>
        </div>
        <div class="col-2">
            <button type="submit" class="btn btn-success btn-lg" style="width: 100%;">Salvar</button>
        </div>
    </div>
  </form>
  <script>
  $('.datepicker').datepicker({
    format: 'dd/mm/yyyy',
    language: 'pt-BR',
    autoclose: true
  });
</script>
{% endblock content %}

espacofacil_api/templates/app/occupancy_list.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<head>
    <meta name="csrf-token" content="{{ csrf_token }}">
</head>
<h1>Realizando Agendamento da Sala {{ room.nameRoom }}</h1>
<div class="container-fullscreen" data-idroom="{{idRoom}}" id="container">
    {% csrf_token %}
    <div class="calendar-container">
        <div id="calendar" class="calendar"></div>
    </div>
</div>

<div id="schedule-modal" class="modal-overlay">
    <div class="modal-content">
        <span class="close-button">&times;</span>
        <h3 id="modal-date-title" class="h3">Agendar Horário</h3>
        
        <table >
            <thead>
                <tr>
                    <td colspan="3">
                        <h4 class="h4" style="margin-left: 15px;">Novo Horário</h4>
                    </td>
                </tr>
                <tr>
                    <th>Ocupante</th>
                    <th>Hora Inicial</th>
                    <th>Hora Final</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="td-novo-horario">
                        <input type="text" name="occupantRoom" id="occupantRoom" class="form-control">
                    </td>
                    <td class="td-novo-horario">
                        <input class="form-control" type="time" name="time_start" id="time_start">
                    </td>
            
                    <td class="td-novo-horario">
                        <input class="form-control" type="time" name="time_end" id="time_end">
                    </td>
                </tr>
                <tr>
                    <td colspan="3" class="td-novo-horario">
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" role="switch" id="recurrent-schedule-checkbox">
                            <label class="form-check-label" for="recurrent-schedule-checkbox">
                                Agendamento recorrente
                            </label>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>

        <div id="recurrent-schedule-section" style="display: none;">
            <hr>
            <h4 class="h4">Detalhes da Recorrência</h4>
            <div class="row">
                <div class="col-12 mb-3">
                    <label class="form-label">Repetir nos dias:</label>
                    <div class="d-flex justify-content-around">
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="checkbox" name="weekday" id="weekday-1" value="0">
                            <label class="form-check-label" for="weekday-1">Seg</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="checkbox" name="weekday" id="weekday-2" value="1">
                            <label class="form-check-label" for="weekday-2">Ter</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="checkbox" name="weekday" id="weekday-3" value="2">
                            <label class="form-check-label" for="weekday-3">Qua</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="checkbox" name="weekday" id="weekday-4" value="3">
                            <label class="form-check-label" for="weekday-4">Qui</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="checkbox" name="weekday" id="weekday-5" value="4">
                            <label class="form-check-label" for="weekday-5">Sex</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="checkbox" name="weekday" id="weekday-6" value="5">
                            <label class="form-check-label" for="weekday-6">Sáb</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="checkbox" name="weekday-0" id="weekday-0" value="6">
                            <label class="form-check-label" for="weekday-0">Dom</label>
                        </div>
                    </div>
                </div>
                <div class="col-6">
                    <label for="recurrent-start-date" class="form-label">Início da Repetição:</label>
                    <input type="date" class="form-control" id="recurrent-start-date">
                </div>
                <div class="col-6">
                    <label for="recurrent-end-date" class="form-label">Fim da Repetição:</label>
                    <input type="date" class="form-control" id="recurrent-end-date">
                </div>
            </div>
        </div>
        <table>
            <tbody>
                <tr>
                    <td colspan="3">
                        <button type="button" id="add-schedule-button" class="btn btn-success adicionar-horario">+ Adicionar Horário</button>                    </td>
                </tr>
            </tbody>
        </table>
        
        <hr>

        <div id="schedule-list">
            <table>
                <thead>
                    <tr>
                        <td colspan="4">
                            <h4 class="h4" style="margin-left: 15px;">Horarios agendados</h4>
                        </td>
                    </tr>
                    <tr>
                        <th>Ocupante</th>
                        <th>Hora Inicial</th>
                        <th>Hora Final</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody id="list">
                    </tbody>
            </table>
        </div>
    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/pt.js"></script>
<script src="{% static 'js/calendar.js' %}"></script>
{% endblock %}

espacofacil_api/templates/app/room_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<h1>Excluindo Espaço</h1>

    <h3 class="h3">Excluir Espaço?</h3>
    <hr>
    <p class="lead">Tem certeza que deseja excluir esse espaço <strong class="strong"> {{room.nameRoom}} </strong> ?</p>
    <form method="POST">
        {% csrf_token %}
        <div class="row g-3">
            <div class="offset-8 col-2">
                <a href="javascript:history.back()" class="btn btn-primary btn-lg">Cancelar</a>
            </div>
            <div class="col-2">
                <button type="submit" class="btn btn-danger btn-lg" style="width: 100%;">Excluir Espaço</button>
            </div>
        </div>
    </form>
{% endblock content %}



    

espacofacil_api/templates/app/room_detail.html
{% extends "base.html" %}

{% load static %}

{% block content %}

  <h1>Visualizando detalhes do Espaço</h1>

  
  <h3 class="h3">Detalhes:</h3>
  <div class="row">
    <p class="col-6 lead">Nome:<span class="text-muted"> {{ room.nameRoom }}</span></p>
    <p class="col-6 lead">Capacidade:<span class="text-muted"> {{ room.headCount }} pessoas</span></p>
    <p class="col-6 lead">Gerente:<span class="text-muted"> {{ room.roomManager.name }}</span></p>
  </div>

  <hr>
  
  <h3 class="h3">Equipamentos no Espaço:</h3>
  {% if equipment %}
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">Equipamento</th>
          <th scope="col">Quantidade</th>
        </tr>
      </thead>
      <tbody>
        {% for equip in equipment %}
        <tr>
          <td>{{ equip.equipment.nameEquipment }}</td>
          <td>{{ equip.amount }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>Nenhum equipamento cadastrado.</p>
  {% endif %}


{% endblock %}

espacofacil_api/templates/app/room_form.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="table-container">
    {% if form.instance.pk %}
        <h1>Editando Espaço</h1>
    {% else %}
        <h1>Adicionando Espaço</h1>
        <br>
    {% endif %}

    <form method="post" class="needs-validation" novalidate>
        {% csrf_token %}
        <fieldset>
            <legend class="h4">Detalhes do Espaço</legend>
            <hr>
            <div class="row">
                <div class="mb-3 col-8">
                    {{ form.nameRoom.label_tag }}
                    {{ form.nameRoom }}
                </div>
                <div class="mb-3 col-4">
                    {{ form.headCount.label_tag }}
                    {{ form.headCount }}
                </div>
                <div class="mb-3 col-12">
                    {{ form.roomManager.label_tag }}
                    {{ form.roomManager }}
                </div>
            </div>

        </fieldset>
        <br>
        <fieldset>
            <legend class="h4">Equipamentos</legend>
            <hr>
            {{ formset.management_form }}
            <div id="equipments" class="mb-3">
                {% for form in formset %}
                    <div class="equipment-form-container row">
                        <div class="mb-3 col-8">
                            {{ form.equipment.label_tag }}
                            {{ form.equipment }}
                        </div>
                        <div class="mb-3 col-4">
                            {{ form.amount.label_tag }}
                            {{ form.amount }}
                        </div>
                        <div class="mb-3 col-6">
                            {{ form.DELETE }} <label for="{{ form.DELETE.id_for_label }}">Remover Equipamento</label>
                        </div>
                        {{ form.id }}
                        {{ form.room }}
                        {{ form.errors }}
                    </div>
                {% endfor %}
            </div>
        </fieldset>
        <fieldset>
            <legend class="h4">Horários Disponíveis</legend>
            <hr>
            {{ timeSlotFormset.management_form }}
            <div id="timeslots" class="mb-3">
                {% for form in timeSlotFormset %}
                    <div class="timeslot-form-container row">
                        <div class="mb-3 col-2">
                            {{ form.time_start.label_tag }}
                            {{ form.time_start }}
                        </div>
                        <div class="mb-3 col-2">
                            {{ form.time_end.label_tag }}
                            {{ form.time_end }}
                        </div>
                        <div class="mb-3 col-2">
                            {{ form.interval.label_tag }}
                            {{ form.interval }}
                        </div>
                        <div class="mb-3 col-2">
                            {{ form.DELETE }} <label for="{{ form.DELETE.id_for_label }}">Remover Intervalo</label>
                        </div>
                        {{ form.id }}
                        {{ form.room }}
                        {{ form.errors }}
                    </div>
                {% endfor %}
            </div>
        </fieldset>
        <div class="row g-3">
            <div class="offset-8 col-2">
                <a href="javascript:history.back()" class="btn btn-danger btn-lg">Cancelar</a>
            </div>
            <div class="col-2">
                <button type="submit" class="btn btn-success btn-lg" style="width: 100%;">Salvar</button>
            </div>
        </div>
    </form>
    
    <script src="{% static 'js/addItem.js' %}"></script>
    <script>
        (function () {
    'use strict'

    var forms = document.querySelectorAll('.needs-validation')

    Array.prototype.slice.call(forms)
        .forEach(function (form) {
        form.addEventListener('submit', function (event) {
            if (!form.checkValidity()) {
            event.preventDefault()
            event.stopPropagation()
            }

            form.classList.add('was-validated')
        }, false)
        })
    })()
    </script>
</div>
{% endblock content %}

espacofacil_api/templates/app/room_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="table-container">
  <h1>Espaços</h1>
  <button class="button-registry">
    <a href={% url "room_create" %} >+ Adicionar Espaço</a>
  </button>
 
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nome</th>
        <th scope="col">Capacidade</th>
        <th scope="col">Responsável</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody>
        {% for room in room_list %}
        <tr>
            <th scope="row">{{room.pk}}</th>
            <td>{{room.nameRoom}}</td>
            <td>{{room.headCount}}</td>
            <td>{{room.roomManager.name}}</td>
            <td class="actions">
              <button class="btn btn-outline-primary" onclick="window.location.href='{% url 'room_update' pk=room.pk %}'">
                Editar
              </button>

              <button class="btn btn-outline-info" onclick="window.location.href='{% url 'room_detail' pk=room.pk %}'">
                Detalhes
              </button>
               
              <button class="btn btn-outline-danger" onclick="window.location.href='{% url 'room_delete' pk=room.pk %}'">
                Excluir
              </button>

              <button class="btn btn-outline-success" onclick="window.location.href='{% url 'occupancy_list' idRoom=room.pk %}'">
                Agendar
              </button>
                
            </td>
          </tr>
        {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

espacofacil_api/templates/app/user_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<h1>Excluindo Usuário</h1>

    <h3 class="h3">Excluir Usuário?</h3>
    <hr>
    <p class="lead">Tem certeza que deseja excluir esse usuário <strong> {{user.name}} </strong> ?</p>
    <form method="POST">
        {% csrf_token %}
        <div class="row g-3">
            <div class="offset-8 col-2">
                <a href="javascript:history.back()" class="btn btn-primary btn-lg">Cancelar</a>
            </div>
            <div class="col-2">
                <button type="submit" class="btn btn-danger btn-lg" style="width: 100%;">Excluir Espaço</button>
            </div>
        </div>  
    </form>
{% endblock content %}


    